apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rowdenb/helm-webapp.git
    targetRevision: main
    path: charts/webapp2
    helm:
      valueFiles:
        - values.yaml  # or values/dev.yaml if using per-environment overrides
  destination:
    server: https://kubernetes.default.svc
    namespace: webappns
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
  syncWave: "1"
